### ISSUE TITLE
Module not work

### ISSUE THREAD

**Issue by pouic13** [easyw/kicad-3d-models-in-freecad#14]
Hi, i try to test your module but i cannot understand how to lunch... 
I install "CadQuery" from https://github.com/dcowden/cadquery

I try to lunch "cq-ex2.FCMacro" (it's reside to my .Freecad/Macro but it's same if i try to lunch directly from your directory) and i receive  this error : 
```
Traceback (most recent call last):
  File "/home/hpc66-jo/.FreeCAD/Macro/cq-ex2.FCMacro", line 23, in <module>
    App.setActiveDocument("Ex000_Introduction")
<class 'Base.FreeCADError'>: Try to activate unknown document 'Ex000_Introduction'
```
 
Can you tell me how to use your script please ?

thank.
Jonathan.

**Comment by easyw** [comment]
Please go to
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator
and download
https://github.com/easyw/kicad-3d-models-in-freecad/blob/master/cadquery/FCAD_script_generator/FC-script-generator-starter-Guide.pdf?raw=true
