### ISSUE TITLE
Adding component with new parameters

### ISSUE THREAD

**Issue by strombom** [easyw/kicad-3d-models-in-freecad#153]
I'm trying to add an inductor, http://katalog.we-online.de/pbs/datasheet/74435580680.pdf

Would it be the correct approach to add it to FCAD_script_generator\Inductors_SMD?

The available parameters are:

Params = namedtuple("Params", [
    'L',   # package length
    'W',   # package width
    'T',   # package height
    'pb',   # pin band
    'pt',   # pin thickness
    'series',    # Inductor Series
    'modelName', # modelName
    'rotation' # rotation if required
])

For the inductor in question I would need to remove the pb parameter and add pin length and width.

Adding new parameters breaks the existing models that are already in the script. 

How would I modify the script without breaking the existing models?

**Comment by easyw** [comment]
If you look at: "L_Vishay_IHSM-3825" 
you can see there is already a second parameters in the pb field...
The parsed act differently if there is one or two parameters.
```
 pb = 0.6, # pin band 
```
or
```
 pb = (1.91,4.32), # pin band 
```
