### ISSUE TITLE
Is there something wrong with the repository?

### ISSUE THREAD

**Issue by Misca1234** [easyw/kicad-3d-models-in-freecad#167]
I am trying to push an update but get an error message

$ git remote -v

origin  https://github.com/Misca1234/kicad-3d-models-in-freecad.git (fetch)
origin  https://github.com/Misca1234/kicad-3d-models-in-freecad.git (push)
upstream        https://github.com/easyw/kicad-3d-models-in-freecad (fetch)
upstream        https://github.com/easyw/kicad-3d-models-in-freecad (push)

$ git push upstream Split_ACDC_DCDC_into_ACDC_and_DCDC_2

remote: Permission to easyw/kicad-3d-models-in-freecad.git denied to Misca1234.
fatal: unable to access 'https://github.com/easyw/kicad-3d-models-in-freecad/': The requested URL returned error: 403

**Comment by Misca1234** [comment]
Yes, i know, I have made several pushes before but now it does not work any more

**Comment by easyw** [comment]
Hi, may this link could help
https://stackoverflow.com/questions/7438313/pushing-to-git-returning-error-code-403-fatal-http-request-failed

**Comment by Misca1234** [comment]
Jee, I found the same link yesterday, I will check up my credentials today to see if it is solved

**Comment by Misca1234** [comment]
Do you think there is some clash when i got larger "admin" rights on the kicad repositories ?

**Comment by Misca1234** [comment]
i pushed it to my lokal fork instead and was able to push it your
