### ISSUE TITLE
phoenix connector scripts not running

### ISSUE THREAD

**Issue by Shackmeister** [easyw/kicad-3d-models-in-freecad#175]
@poeschlr I'm currently going through the models and was planning to fix the library names of the phoenix connectors. I do however have some troubles with running your script, can you please check if you have some uncommited changes?

**Comment by easyw** [comment]
Hi @shackmeister
please note that CQ 1.2 has some issue
https://github.com/jmwright/cadquery-freecad-module/issues/120

I use CQ v1.1
https://github.com/jmwright/cadquery-freecad-module/tree/19994ffd488224d0eb9540e083a7cbeab99d4db7

**Comment by Shackmeister** [comment]
apparently I just needed to remove a few unneeded lines to fix it. I'm making a PR later
