### ISSUE TITLE
Render of PAD as circle

### ISSUE THREAD

**Issue by jneiva08** [easyw/kicad-3d-models-in-freecad#180]
Hi, I don't know if its this the right place to report.

When try to open new footprint it shows the pad as circle, instead of a square with rounded corners.

I'm using freecad 0.17 with StepUp version 7.3.3.1
footprint tested: [link](https://github.com/KiCad/kicad-footprints/blob/master/Package_DFN_QFN.pretty/QFN-64-1EP_9x9mm_P0.5mm_EP7.7x7.7mm.kicad_mod)

Thanks

**Comment by easyw** [comment]
Hi @jneiva08 
the right place would be this repo
https://github.com/easyw/kicadStepUpMod

BTW StepUp hanldes round rectangles only when designing and exporting the footprint with FC Sketcher and not when importing it in FC.
If you want you can rise an issue at the kicadStepUpMod repo, that will help me in not forgetting to handle also the importing.
Thx
