### ISSUE TITLE
DC to DC converter generator no longer works

### ISSUE THREAD

**Issue by stambaughw** [easyw/kicad-3d-models-in-freecad#224]
I was working on a new DC to DC converter model but the generator no longer seems to work.  Using commit fb2c76aa of this repo, running command:

'C:\Program
 Files\FreeCAD 0.17\bin\FreeCAD.exe' .\main_generator.py "Converter_DCDC_XP_POWER_JTExxxxDxx_THT"

I get the following error in FreeCAD

CadQuery 1.2.0
CadQuery is a parametric scripting API for creating and traversing CAD models
Author: David Cowden
License: Apache-2.0
Website: https://github.com/dcowden/cadquery
FC Version 
['0', '17', '13519 (Git)', 'git://github.com/FreeCAD/FreeCAD.git releases/FreeCAD-0-17', '2018/04/22 05:49:26', 'releases/FreeCAD-0-17', '1a8b868018f45ea486c0023fdbfeb06febc1fb89']FC Version 017
CQ 030 doesn't open example file
File format not supported: Converter_DCDC_XP_POWER_JTExxxxDxx_THT 

It appears that something has been recently broken.  This command used to work just a week or so ago.

**Comment by easyw** [comment]
@Misca1234
would you please have a look at this issue?
Thx

**Comment by Misca1234** [comment]
yes, give me a minute

**Comment by Misca1234** [comment]
Hmm, works for me

![bild](https://user-images.githubusercontent.com/25547797/48305425-6cb52c80-e52a-11e8-9925-be53ac901cdb.png)


CadQuery 1.0.0
CadQuery is a parametric scripting API for creating and traversing CAD models
Author: David Cowden
License: Apache-2.0
Website: https://github.com/dcowden/cadquery
FC Version 
['0', '17', '11223 (Git)', 'git://github.com/FreeCAD/FreeCAD.git master', '2017/06/03 11:46:05', 'master', '88bd341ad2da7399719d350bf9f715297d8d9f33']FC Version 017

Running...
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC\main_generator.py
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC
['', '\\main_generator.py']
Converter_DCDC
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\

Converter_DCDC_XP_POWER_JTExxxxDxx_THT

make_case
make_case_top
make_pins_tht
{(0.8240000009536743, 0.8199999928474426, 0.781000018119812): 'metal grey pins', (0.14800000190734863, 0.14499999582767487, 0.14499999582767487): 'black body'}
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.step exported
License addition successful
######################################################################
[<Part::PartFeature>]
######################################################################
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.wrl written
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.FCStd saved
File format not supported: Converter_DCDC_XP_POWER_JTExxxxDxx_THT

**Comment by Misca1234** [comment]
Try

**C:\Program Files\FreeCAD 0.17\bin\FreeCAD.exe' main_generator.py Converter_DCDC_XP_POWER_JTExxxxDxx_THT**

**Comment by easyw** [comment]
@Misca1234
Waine is using latest CQ 1.2

**Comment by Misca1234** [comment]
I can try to download it but if it is an error in CQ we might have major problems everywhere

**Comment by easyw** [comment]
I built recently some models with CQ 1.2 without issues

**Comment by Misca1234** [comment]
I installed cadquery 1.2 and it still works for me


........................../FreeCAD_0.17.11223_x64_dev_win/bin/FreeCAD.exe main_generator.py Converter_DCDC_XP_POWER_JTExxxxDxx_THT


![bild](https://user-images.githubusercontent.com/25547797/48310062-1f1add00-e587-11e8-82af-df226460ba5e.png)


CadQuery 1.0.0
CadQuery is a parametric scripting API for creating and traversing CAD models
Author: David Cowden
License: Apache-2.0
Website: https://github.com/dcowden/cadquery
FC Version 
['0', '17', '11223 (Git)', 'git://github.com/FreeCAD/FreeCAD.git master', '2017/06/03 11:46:05', 'master', '88bd341ad2da7399719d350bf9f715297d8d9f33']FC Version 017

Running...
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC\main_generator.py
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC
['', '\\main_generator.py']
Converter_DCDC
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\

Converter_DCDC_XP_POWER_JTExxxxDxx_THT

make_case
make_case_top
make_pins_tht
{(0.8240000009536743, 0.8199999928474426, 0.781000018119812): 'metal grey pins', (0.14800000190734863, 0.14499999582767487, 0.14499999582767487): 'black body'}
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.step exported
License addition successful
######################################################################
[<Part::PartFeature>]
######################################################################
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.wrl written
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.FCStd saved
File format not supported: Converter_DCDC_XP_POWER_JTExxxxDxx_THT

**Comment by Misca1234** [comment]
I have installed the 1.2.0 cadquery into my freecad and it seems to work for me 

![bild](https://user-images.githubusercontent.com/25547797/48310145-3c50ab00-e589-11e8-927d-264b49bc23cb.png)


CadQuery 1.2.0
CadQuery is a parametric scripting API for creating and traversing CAD models
Author: David Cowden
License: Apache-2.0
Website: https://github.com/dcowden/cadquery
FC Version 
['0', '17', '11223 (Git)', 'git://github.com/FreeCAD/FreeCAD.git master', '2017/06/03 11:46:05', 'master', '88bd341ad2da7399719d350bf9f715297d8d9f33']FC Version 017

Running...
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC\main_generator.py
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\Converter_DCDC
['', '\\main_generator.py']
Converter_DCDC
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\

Converter_DCDC_XP_POWER_JTExxxxDxx_THT

make_case
make_case_top
make_pins_tht
{(0.8240000009536743, 0.8199999928474426, 0.781000018119812): 'metal grey pins', (0.14800000190734863, 0.14499999582767487, 0.14499999582767487): 'black body'}
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.step exported
License addition successful
######################################################################
[<Part::PartFeature>]
######################################################################
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.wrl written
C:\Users\stefan\KiCad\NyVersion\kicad-3d-models-in-freecad\cadquery\FCAD_script_generator\_3Dmodels/Converter_DCDC.3dshapes\Converter_DCDC_XP_POWER_JTExxxxDxx_THT.FCStd saved
File format not supported: Converter_DCDC_XP_POWER_JTExxxxDxx_THT

**Comment by stambaughw** [comment]
I did some more testing and I found that there seems to be an issue on my work laptop with window 10 pro.  On my home system with windows 10 home works fine using the same version of FreeCAD and cadquery.   I will try to figure out why my windows 10 pro system doesn't work when I get a chance.  This issue can be closed.  I will report back if I figure out what went wrong.  Sorry about the noise.

**Comment by easyw** [comment]
Thx

**Comment by Misca1234** [comment]
No problem, we are here for you
