### ISSUE TITLE
pinheaders not working

### ISSUE THREAD

**Issue by AnduriI** [easyw/kicad-3d-models-in-freecad#27]
I'm trying to create pin headers with your script (```c:/freecad/bin/freecad make_pinheaders_export_fc.py all```). But FreeCAD just gives an error message:
```
./generated_pinheaders/\PinHeader_Straight_1x02_H06_p1.27mm.step
./generated_pinheaders/Exception while processing file: make_pinheaders_export_fc.py [local variable 'LIST_license' referenced before assignment]
File format not supported: all 
```
and only created that one .step file. What am I doing wrong?

And a second question, is it possible to create angled pinheaders?

**Comment by easyw** [comment]
@AnduriI 
fixing on the go

**Comment by easyw** [comment]
ok, it should be fixed now
ths for reporting :)
