### ISSUE TITLE
The generator directory is a mess. How should we reorganize it?

### ISSUE THREAD

**Issue by poeschlr** [easyw/kicad-3d-models-in-freecad#28]
@easyw, @SchrodingersGat, @Shackmeister, @DASFrank, @metacollin:
How should the generators be organized.
For me 3 options come to mind: (sorted from most effort to least effort.)

Option 1:
Go for depth
![option1](https://cloud.githubusercontent.com/assets/18327350/23557680/201ff3f8-0031-11e7-8d1c-3b377c68ac27.png)

Option 2:
My current effort. A bit of depth but also a lot of directories in the root folder.
![option2](https://cloud.githubusercontent.com/assets/18327350/23557810/9da282e6-0031-11e7-8b77-2f5a59db772d.png)

Option 3:
Focus on a uniform repo
Effort by Oliver (as i understand it. I might have interpreted it wrong.) This is the solution that creates the least amount of work.
![option3](https://cloud.githubusercontent.com/assets/18327350/23557851/c9b5373e-0031-11e7-8712-81f9e1340deb.png)

I vote for option 1 because i think it is the most future proof. (It will work even if we have 10 times the current generator scripts.)
Option 2 generates nearly the same amount of work as option 1 does. (Still has a cluttered root directory)
Option 3 could be a quick and dirty fix to get a uniform repository.

Any other suggestions?

**Comment by easyw** [comment]
@poeschlr, @SchrodingersGat, @Shackmeister, @DASFrank, @metacollin 
I was thinking of something like that:
![git-structure](https://cloud.githubusercontent.com/assets/3032347/23571247/6e1b82d4-0068-11e7-959d-862bca4b9654.png)
The structure will be similar to https://github.com/KiCad and when a family script generator is added, only one dir will be added to the repo. Output dir should be maintained empty on-line, but its structure is useful to test and generate models locally.
The reorganizing would be very easy but the result would be much cleaner than now...
What do you think?

**Comment by poeschlr** [comment]
@easyw is my interpretation correct that what you suggest is very similar to option 2 but with the output directory moved to a separate directories within the root directory? 
By the way i like the mention of the _tools folder. I would do this this regardless of how the rest of the repo is organized.

**Comment by SchrodingersGat** [comment]
Whichever way we go, we need to reduce the amount of duplicated files that are floating around. Currently it is a nightmare for maintenance.

e.g. a single license source script that gets copied into each file.

There's also much duplication of code which my PR https://github.com/easyw/kicad-3d-models-in-freecad/pull/24 tries to address.

The other thing to address is naming convention. Currently the different scripts have random naming and there is no need to have multiple .sh / .bat files that just serve to pass different arguments through...

**Comment by easyw** [comment]
> e.g. a single license source script that gets copied into each file.

the new add_license.py is called with default license or with a custom one which is a variable in the main script

> The other thing to address is naming convention

about naming convention we could have for main files:
- main_generator.py 
- cq_parameters.py
- **create_model.bat**(sh) '**model_name**' or '**all**' to create all family models
other side files may be named with some grade of freedom
I like to have a single launcher inside the specific family folder to make the user approach to generation easier...
in **_tool** directory I would like to have:
- cq_cad_tools.py
- exportPartToVRML.py
- shaders.py
- also the 'cq_helpers.py' made by @poeschlr :D 
Version checking could be merged as function in cq_cad_tools.py
we could also add a DIR for '**screenshots**' of the generated models/family and a '**doc**' DIR for extra documentation
a **todo.md** and **readme.md** file will be at root to explain main usage and requirements
(FC 0.15 is best suggested for STEP generation and CQ 0.52 actual release which is tested ATM fine for all models)
Is this a good compromise for all of us?
Thx
Maurice

**Comment by poeschlr** [comment]
Looks good

> create_model.bat(sh) 'model_name' or 'all'

This means i need to change my scripts.
(Currently i'm expecting filter=model_name or filter=*)
But this is easily done.

regarding the cq_helpers.py script: I need to play around a bit with that. currently i have a copy of it in all cq_models directories. I need to find a way to have a different python path for when the model is generated as standalone in the cadquery workbench and when it is generated from the export scripts.
(I'm sure there is a way. I was lacy when i made my last cleanup and i wanted to generate my models.)
I will look into this stuff today.

**Comment by easyw** [comment]
@poeschlr  @SchrodingersGat 
I just started a refactory of the structure...
ATM I've done it for resistors_SMD... hte process to move the scripts to the new structure is very easy ...
I'm going to move all the scripts gradually...
Maurice

**Comment by easyw** [comment]
capacitors_SMD done 😸

**Comment by easyw** [comment]
capacitors_radial_SMD done  :grinning:

**Comment by easyw** [comment]
DIP_packages done 😸

**Comment by SchrodingersGat** [comment]
🥇

**Comment by easyw** [comment]
GullWings QFP_SOIC_SSOP_TSSOP_SOT refactored 😸

**Comment by easyw** [comment]
Pin Headers, Box Headers, Capacitors Radial THT completed! Only @poeschlr model scripts need to be slightly refactored to point to **_tools** and to generate in **_3Dmodels** sub dir ...

**Comment by easyw** [comment]
@poeschlr  @SchrodingersGat 
you may condìsider useful this folder:
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/WIP
I added some WIP scripts...
1) option to generate molded QFN, and then BGA
![molded-qfn](https://cloud.githubusercontent.com/assets/3032347/24525155/93d04f6e-1599-11e7-8bd0-a1fb62bb81f1.png)
2) option to load footprint beside the 3D generated model to easily check the result for all the family
(latest kicad StepUp Mod 4.1.2.8 needed)
![molded-qfn-footprint](https://cloud.githubusercontent.com/assets/3032347/24525397/6353619a-159a-11e7-92eb-f4a1c7bfde51.png)

**Comment by easyw** [comment]
cleanup completed :)
