### ISSUE TITLE
Extending SMD TO and SOT scripts

### ISSUE THREAD

**Issue by hackscribble** [easyw/kicad-3d-models-in-freecad#50]
Hi @easyw and @Shackmeister 

I've opened this issue to continue the discussion from the PR ... https://github.com/easyw/kicad-3d-models-in-freecad/pull/49

>I'm adding Shackmeister to this conversation...
He did the work to extend sot packages to many asymmetric models and he was suggesting me to improve the generation for other models - @easyw 

> I was considering adding and option to set each pin induvidualy to either a GW or a flat pins... also I was thinking about adding an option in exclude_pins to set a value to 2.5 to only have half of the pin. would be used for TO-252 etc. - @Shackmeister 

Can you confirm that the existing scripts are in this folder?  
https://github.com/easyw/kicad-3d-models-in-freecad/tree/master/cadquery/FCAD_script_generator/GW_QFP_SOIC_SSOP_TSSOP_SOT

Thanks

**Comment by easyw** [comment]
@hackscribble 
yes here they are :smile:

**Comment by hackscribble** [comment]
### Building a list of possible devices to include.  
I will update this comment as I find new ones.

Package | Aliases | Image
---|---|---
TO-268 | D3PAK |  ![image](https://cloud.githubusercontent.com/assets/7076027/25328930/95186abe-28d1-11e7-8cef-f66a2d12012e.png) 
TO-263-7 | D2PAK7 | ![image](https://cloud.githubusercontent.com/assets/7076027/25328995/d4db940a-28d1-11e7-8709-8619e8c0cb96.png) 
TO-263-7 centre lead trimmed | D2PAK7-T, SOT427 | ![image](https://cloud.githubusercontent.com/assets/7076027/25329519/f5e41d5a-28d3-11e7-8912-3a9fcef9acfa.png)
TO-263-5 | D2PAK5 | ![image](https://cloud.githubusercontent.com/assets/7076027/25329023/f9270d8a-28d1-11e7-9436-ab949b32e56e.png) 
TO-263AA | D2PAK3 | ![image](https://cloud.githubusercontent.com/assets/7076027/25329054/1d456edc-28d2-11e7-8973-2078e6c16ef8.png) 
TO-263AB | D2PAK | ![image](https://cloud.githubusercontent.com/assets/7076027/25329102/50d1c228-28d2-11e7-9747-5e42783ac6e7.png) 
TO-252 | DPAK, TO-252AA | ![image](https://cloud.githubusercontent.com/assets/7076027/25329169/8ca4b184-28d2-11e7-8c55-95436cd55ffa.png) 
TO-243AA | SOT-89 | ![image](https://cloud.githubusercontent.com/assets/7076027/25329226/c4cbae1e-28d2-11e7-8545-1ccf05d50d39.png) 
TO-252-3L | DPAK3-T | ![image](https://cloud.githubusercontent.com/assets/7076027/25329365/5f9bdfc2-28d3-11e7-9e5c-ae5f7dc9b342.png)
TO-252-5 | DPAK5-T | ![image](https://cloud.githubusercontent.com/assets/7076027/25329403/7ba62c90-28d3-11e7-974f-c95fa573feef.png)
TO-252-7F | DPAK7F-T | ![image](https://cloud.githubusercontent.com/assets/7076027/25329574/36328734-28d4-11e7-8c70-172b5db2f689.png)
TO-263-4 center lead trimmed | SOT-426 | ![image](https://cloud.githubusercontent.com/assets/7076027/25329628/7ef18f74-28d4-11e7-93d7-57fcafe8739d.png)

**Comment by hackscribble** [comment]
@easyw @Shackmeister If you know of other packages that should be added to the list, please suggest them.  I will do some more searching over the next couple of days and then start to collect drawings / dimensions.

**Comment by hackscribble** [comment]
Looks like most of the packages in the earlier comment boil down to the 11 models in the tables below.  This is where I am going to focus.

There are some gaps in `TO_SOT_Packages_SMD.pretty` so my first job is to create the missing footprints and check that the existing ones are correct.

### DPAK

| Pins | Cropped pin | Aliases                   | KiCad footprint     |
|------|-------------|---------------------------|----------------------|
| 3    | no          | TO-252-3L                 | x                    |
| 3    | yes         | TO-252AA, SOT-428         | SOT-428              |
| 5    | no          | TO-252-5                  | x                    |
| 5    | yes         | TO-252-5-11               | TO-252-5-11          |

### D2PAK

| Pins | Cropped pin | Aliases                   | KiCad footprint     |
|------|-------------|---------------------------|----------------------|
| 3    | no          | TO-263AA                  | TO-263-3Lead         |
| 3    | yes         | TO-263AB, SOT-404         | SOT-404              |
| 5    | no          | TO-263-5                  | TO-263-5Lead         |
| 5    | yes         | TO-263-4, SOT-426         | x                    |
| 7    | no          | TO-263-7, TO-220-7-4      | TO-220-7Lead_TabPin8 |
| 7    | yes         | TO-263-7 cropped, SOT-427 | x                    |

### D3PAK

| Pins | Cropped pin | Aliases                   | KiCad footprint     |
|------|-------------|---------------------------|----------------------|
| 3    | yes         | TO-268                    | x                    |

**Comment by easyw** [comment]
@hackscribble I'm adding @SchrodingersGat to this conversation...
looking at the models you are evaluating to create with your scripts I would consider your list exhaustive...
Regarding the model already present I would vote to substitute all with the ones coming from your scripts  ... that will give an uniformity to the library (same style, color as per kiCAD materials etc) and also a affordable and easy way to modify / update if needed...
@SchrodingersGat what do you think?
Thx
Maurice

**Comment by SchrodingersGat** [comment]
Agreed, it's not too much effort to add the dimensions for existing models to a script, and that way we have consistency and also the ability to update all models at once

**Comment by hackscribble** [comment]
PR submitted for DPAK, D2PAK and D3PAK footprints: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/47

Once I get feedback on them and finalise them, I will work on the 3D models for them.

**Comment by hackscribble** [comment]
Still work to be done on the pins, the tab shape for TO263 (D2PAK) and generally on TO268 (D3PAK) but the models are coming along nicely.

![image](https://cloud.githubusercontent.com/assets/7076027/25525799/7d74b41e-2c08-11e7-8a71-4fb1a9a07be1.png)

**Comment by Shackmeister** [comment]
Wow, that is awesome man! I'm a huge fan :p thanks for your work

**Comment by easyw** [comment]
Great! Second fan here! ;)

**Comment by easyw** [comment]
I think now we can close it :smile:

**Comment by SchrodingersGat** [comment]
This is looking really good :)

**Comment by Shackmeister** [comment]
hey @hackscribble can you please consider adding the following models:
SOT669
TO252-2

**Comment by hackscribble** [comment]
Hi @Shackmeister 

TO-252-2 is among the models that were merged into the library: https://github.com/KiCad/kicad-library/pull/1204 :smile: 

Happy to add SOT-669 but I won't have time until next week.

**Comment by Shackmeister** [comment]
changed the TO-252-2-Rectifier to use the same model :)

**Comment by Shackmeister** [comment]
perhaps yours is better :P not sure though :package: 
https://forum.kicad.info/t/3d-new-library-for-mechanical-cad-exporting-and-enclosure-design/1763/316
can you please check if other of the missing ones could be made with your script? :)

**Comment by hackscribble** [comment]
From all the current footprints in `TO_SOT_Packages_SMD.pretty`, I've extracted the unique 3D model names.

These are the models which do **not** exist in `TO_SOT_Packages_SMD.3dshapes`, so I will see if can model any of these.

![image](https://cloud.githubusercontent.com/assets/7076027/25823316/99b4b114-3433-11e7-8cf5-e8db4bea13c1.png)

There are also several 3D models that are not referenced any more by a footprint ...

![image](https://cloud.githubusercontent.com/assets/7076027/25823324/a44c64f0-3433-11e7-8825-16e8d05f84dd.png)

**Comment by Shackmeister** [comment]
I already added quite a few of those you listed :) I'll add them in the repo when @maui has had a look at them :)

**Comment by Shackmeister** [comment]
Or you can see the list of freshly added ones here 
https://github.com/easyw/kicad-3d-models-in-freecad/pull/59/files

**Comment by hackscribble** [comment]
If I'm reading your PR right, the only missing ones will be ...

![image](https://cloud.githubusercontent.com/assets/7076027/25824309/d337d1c0-3436-11e7-9a40-4350bb5a0780.png)

I can do the first and last with my current script. The SOT-133n would need a different script. 

About the PQFN:
- maybe it belongs in `Housings_QFN_DFN`?
- so far, I can't find a device that has a pinout / recommended land pattern that matches the footprint :smile:

**Comment by Shackmeister** [comment]
I made the 1333 and 1334 with the QFN script (the ground pins are not connected all the way through but that shouldn't be too much of an issue)

**Comment by Shackmeister** [comment]
If you can fix those I'll brew up a script to make the To50 /powermacro models :)

**Comment by easyw** [comment]
for the 1333 I found a workaround 😜  through the epad 😉

**Comment by Shackmeister** [comment]
Screenshot? :)

**Comment by easyw** [comment]
![sot-1333-1](https://cloud.githubusercontent.com/assets/3032347/25827508/d69b1d1c-344b-11e7-9587-702b8de5e6b7.PNG)
💤 😴 😉

**Comment by Shackmeister** [comment]
Nice :p can you please check the models and perhaps the script when you have time? :)

**Comment by easyw** [comment]
I will
Thx

**Comment by hackscribble** [comment]
There was a commit two days ago to the 3D models for `TO_SOT_Packages_SMD.pretty` ...

https://github.com/KiCad/kicad-library/commit/a3e3dcaf2cee73bb0ad9e06d32805237606908e4

Running my check program against the footprints and models now shows these gaps ...

```
Checking TO_SOT_Packages_SMD (contains 98 modules)
- No 3D model for reference Infineon_PG-HSOF-8-1.wrl in module Infineon_PG-HSOF-8-1.kicad_mod
- No 3D model for reference Infineon_PG-HSOF-8-1.wrl in module Infineon_PG-HSOF-8-1_ThermalVias.kicad_mod
- No 3D model for reference PQFN_8x8.wrl in module PQFN_8x8.kicad_mod
- No 3D model for reference SOT-669_LFPAK.wrl in module SOT-669_LFPAK.kicad_mod
- No 3D model for reference SOT-669_LFPAK_ThermalVias-1.wrl in module SOT-669_LFPAK_ThermalVias-1.kicad_mod
- No 3D model for reference SOT-669_LFPAK_ThermalVias-2.wrl in module SOT-669_LFPAK_ThermalVias-2.kicad_mod
- No 3D model for reference SOT89-3_Housing.wrl in module SOT89-3_Housing.kicad_mod
- No 3D model for reference SOT89-3_Housing_Handsoldering.wrl in module SOT89-3_Housing_Handsoldering.kicad_mod
- No 3D model for reference SOT89-5_Housing.wrl in module SOT89-5_Housing.kicad_mod
- No 3D model for reference SOT89-5_Housing_Handsoldering.wrl in module SOT89-5_Housing_Handsoldering.kicad_mod
- No 3D model for reference TO-252-2_Rectifier.wrl in module TO-252-2_Rectifier.kicad_mod
- No 3D model for reference TO-277A.wrl in module TO-277A.kicad_mod
- 12 module warnings
```

The `TO-220-7Lead_TabPin8` now has a model, so I will drop that from my to do list.  But the `Infineon_PG-HSOF-8-1` and `SOT-669_LFPAK` still need models, so I will add those to my script.

I will also submit a PR for the footprint repo so that the variants (e.g. normal vs different vias) all point to the same 3D model.

**Comment by Shackmeister** [comment]
sounds good :)

**Comment by Shackmeister** [comment]
you should probably check against packages3D instead of kicad-library (packages3D should hopefully not have any og the old wings WRL files)

**Comment by Shackmeister** [comment]
unless your script can handle the TO-50 I can make one :)

**Comment by easyw** [comment]
@hackscribble is there possible to see your checking script? this sounds nice to have! 😄

**Comment by hackscribble** [comment]
@Shackmeister my current script won't do TO-50, it would need me to write a new script.

@easyw sure thing ... https://github.com/hackscribble/kicad-library-utils/blob/add_check_3d_coverage/pcb/check_3d_coverage.py  I have submitted a PR in case the librarians want to add it to the kicad-library-utils.  The current version needs editing to change to `packages3D` repo from `kicad-library` repo but I will make that a command line argument in the next version, once I get any feedback generally on it from the librarians.

**Comment by hackscribble** [comment]
SOT-669 done.  I need to submit a PR for the footprint to remove the old position and scaling values.

![image](https://cloud.githubusercontent.com/assets/7076027/26067794/3e47c3ce-3993-11e7-8d83-00eaf2da5746.png)

**Comment by Shackmeister** [comment]
@hackscribble from what I can see in your scriptchecking the .Pretty foldet is outdated, you should probably grab the newest and rerun it

**Comment by hackscribble** [comment]
I thought I pulled the latest yesterday, but I'll double check.

**Comment by Shackmeister** [comment]
kicad-library is filled with all the old models while packages3D only have the new models which also have the step part. So if possible all the models in kicad-library should be remade in freecad :)

**Comment by hackscribble** [comment]
Pr submitted for tidying up the SOT-669 and HSOF-8-1 footprints: https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/54

That leaves the SOT-89-3 model to finish.
